{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "name": "auth-service",
    "namespace": "novapay-prod"
  },
  "spec": {
    "progressDeadlineSeconds": 600,
    "replicas": 3,
    "revisionHistoryLimit": 10,
    "selector": {
      "matchLabels": {
        "app": "auth-service"
      }
    },
    "strategy": {
      "rollingUpdate": {
        "maxSurge": "25%",
        "maxUnavailable": "25%"
      },
      "type": "RollingUpdate"
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "auth-service"
        }
      },
      "spec": {
        "containers": [
          {
            "env": [
              {
                "name": "NODE_ENV",
                "value": "lab"
              },
              {
                "name": "PORT",
                "value": "3001"
              },
              {
                "name": "SERVICE_NAME",
                "value": "auth-service"
              },
              {
                "name": "SHUTDOWN_TIMEOUT_MS",
                "value": "55000"
              },
              {
                "name": "DB_HOST",
                "value": "postgres"
              },
              {
                "name": "DB_PORT",
                "value": "5432"
              },
              {
                "name": "DB_NAME",
                "value": "novapay"
              },
              {
                "name": "DB_USERNAME",
                "value": "novapay_user"
              },
              {
                "name": "DB_PASSWORD",
                "value": "labpass123"
              },
              {
                "name": "REDIS_ENDPOINT",
                "value": "redis"
              }
            ],
            "image": "283298108838.dkr.ecr.us-east-1.amazonaws.com/novapay-poc/auth:v1.0.0",
            "imagePullPolicy": "IfNotPresent",
            "livenessProbe": {
              "failureThreshold": 3,
              "httpGet": {
                "path": "/health",
                "port": 3001,
                "scheme": "HTTP"
              },
              "initialDelaySeconds": 15,
              "periodSeconds": 10,
              "successThreshold": 1,
              "timeoutSeconds": 1
            },
            "name": "auth-service",
            "ports": [
              {
                "containerPort": 3001,
                "protocol": "TCP"
              }
            ],
            "readinessProbe": {
              "failureThreshold": 3,
              "httpGet": {
                "path": "/health",
                "port": 3001,
                "scheme": "HTTP"
              },
              "initialDelaySeconds": 5,
              "periodSeconds": 5,
              "successThreshold": 1,
              "timeoutSeconds": 1
            },
            "resources": {
              "limits": {
                "cpu": "1",
                "memory": "1Gi"
              },
              "requests": {
                "cpu": "250m",
                "memory": "512Mi"
              }
            },
            "securityContext": {
              "allowPrivilegeEscalation": false,
              "capabilities": {
                "drop": [
                  "ALL"
                ]
              },
              "readOnlyRootFilesystem": true
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "volumeMounts": [
              {
                "mountPath": "/tmp",
                "name": "tmp"
              }
            ]
          }
        ],
        "dnsPolicy": "ClusterFirst",
        "restartPolicy": "Always",
        "schedulerName": "default-scheduler",
        "securityContext": {
          "runAsNonRoot": true,
          "runAsUser": 1000,
          "seccompProfile": {
            "type": "RuntimeDefault"
          }
        },
        "serviceAccount": "auth-service-sa",
        "serviceAccountName": "auth-service-sa",
        "terminationGracePeriodSeconds": 60,
        "tolerations": [
          {
            "effect": "NoSchedule",
            "key": "novapay.io/payment-critical",
            "operator": "Exists"
          }
        ],
        "topologySpreadConstraints": [
          {
            "labelSelector": {
              "matchLabels": {
                "app": "auth-service"
              }
            },
            "maxSkew": 1,
            "topologyKey": "topology.kubernetes.io/zone",
            "whenUnsatisfiable": "DoNotSchedule"
          }
        ],
        "volumes": [
          {
            "emptyDir": {},
            "name": "tmp"
          }
        ]
      }
    }
  }
}
