{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "auth-service",
    "namespace": "novapay-prod"
  },
  "spec": {
    "ports": [
      {
        "port": 80,
        "targetPort": 3001
      }
    ],
    "selector": {
      "app": "auth-service"
    },
    "type": "ClusterIP"
  }
}
