apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"auth-service","namespace":"novapay-prod"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"auth-service"}},"template":{"metadata":{"labels":{"app":"auth-service"}},"spec":{"containers":[{"env":[{"name":"NODE_ENV","value":"lab"},{"name":"PORT","value":"3001"},{"name":"SERVICE_NAME","value":"auth-service"},{"name":"SHUTDOWN_TIMEOUT_MS","value":"55000"},{"name":"DB_HOST","value":"postgres"},{"name":"DB_PORT","value":"5432"},{"name":"DB_NAME","value":"novapay"},{"name":"DB_USERNAME","value":"novapay_user"},{"name":"DB_PASSWORD","value":"labpass123"},{"name":"REDIS_ENDPOINT","value":"redis"}],"image":"628306021196.dkr.ecr.us-east-1.amazonaws.com/novapay-poc/auth:v1.0.0","livenessProbe":{"httpGet":{"path":"/health","port":3001},"initialDelaySeconds":15,"periodSeconds":10},"name":"auth-service","ports":[{"containerPort":3001}],"readinessProbe":{"httpGet":{"path":"/health","port":3001},"initialDelaySeconds":5,"periodSeconds":5},"resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"250m","memory":"512Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true},"volumeMounts":[{"mountPath":"/tmp","name":"tmp"}]}],"securityContext":{"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}},"serviceAccountName":"auth-service-sa","terminationGracePeriodSeconds":60,"tolerations":[{"effect":"NoSchedule","key":"novapay.io/payment-critical","operator":"Exists"}],"topologySpreadConstraints":[{"labelSelector":{"matchLabels":{"app":"auth-service"}},"maxSkew":1,"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"DoNotSchedule"}],"volumes":[{"emptyDir":{},"name":"tmp"}]}}}}
  creationTimestamp: "2026-05-20T11:10:07Z"
  generation: 3
  name: auth-service
  namespace: novapay-prod
  resourceVersion: "149788"
  uid: 0ff3f562-2a2a-4eaa-b9c3-b5e3d827a3cd
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: auth-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-service
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: lab
        - name: PORT
          value: "3001"
        - name: SERVICE_NAME
          value: auth-service
        - name: SHUTDOWN_TIMEOUT_MS
          value: "55000"
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: novapay
        - name: DB_USERNAME
          value: novapay_user
        - name: DB_PASSWORD
          value: labpass123
        - name: REDIS_ENDPOINT
          value: redis
        image: 628306021196.dkr.ecr.us-east-1.amazonaws.com/novapay-poc/auth:v1.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: auth-service
        ports:
        - containerPort: 3001
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: auth-service-sa
      serviceAccountName: auth-service-sa
      terminationGracePeriodSeconds: 60
      tolerations:
      - effect: NoSchedule
        key: novapay.io/payment-critical
        operator: Exists
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: auth-service
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      volumes:
      - emptyDir: {}
        name: tmp
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2026-05-20T11:25:05Z"
    lastUpdateTime: "2026-05-20T11:25:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-05-20T11:24:39Z"
    lastUpdateTime: "2026-05-20T11:25:05Z"
    message: ReplicaSet "auth-service-79b8cc9dd4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
