{
  "apiVersion": "argoproj.io/v1alpha1",
  "kind": "Rollout",
  "metadata": {
    "annotations": {
      "rollout.argoproj.io/revision": "1"
    },
    "name": "payment-service",
    "namespace": "novapay-prod"
  },
  "spec": {
    "replicas": 3,
    "revisionHistoryLimit": 3,
    "selector": {
      "matchLabels": {
        "app": "payment-service"
      }
    },
    "strategy": {
      "blueGreen": {
        "activeService": "payment-service-active",
        "autoPromotionEnabled": false,
        "previewService": "payment-service-preview",
        "scaleDownDelaySeconds": 60
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "payment-service"
        }
      },
      "spec": {
        "containers": [
          {
            "env": [
              {
                "name": "NODE_ENV",
                "value": "production"
              },
              {
                "name": "PORT",
                "value": "3002"
              },
              {
                "name": "SERVICE_NAME",
                "value": "payment-service"
              },
              {
                "name": "SHUTDOWN_TIMEOUT_MS",
                "value": "55000"
              },
              {
                "name": "DB_HOST",
                "value": "postgres"
              },
              {
                "name": "DB_PORT",
                "value": "5432"
              },
              {
                "name": "DB_NAME",
                "value": "novapay"
              },
              {
                "name": "DB_USERNAME",
                "value": "novapay_user"
              },
              {
                "name": "DB_PASSWORD",
                "value": "labpass123"
              }
            ],
            "image": "283298108838.dkr.ecr.us-east-1.amazonaws.com/novapay-poc/charge:v1.0.0",
            "livenessProbe": {
              "failureThreshold": 3,
              "httpGet": {
                "path": "/health",
                "port": 3002
              },
              "initialDelaySeconds": 15,
              "periodSeconds": 10
            },
            "name": "payment-service",
            "ports": [
              {
                "containerPort": 3002,
                "protocol": "TCP"
              }
            ],
            "readinessProbe": {
              "failureThreshold": 3,
              "httpGet": {
                "path": "/health",
                "port": 3002
              },
              "initialDelaySeconds": 5,
              "periodSeconds": 5
            },
            "resources": {
              "limits": {
                "cpu": "1",
                "memory": "1Gi"
              },
              "requests": {
                "cpu": "250m",
                "memory": "512Mi"
              }
            },
            "securityContext": {
              "allowPrivilegeEscalation": false,
              "capabilities": {
                "drop": [
                  "ALL"
                ]
              },
              "readOnlyRootFilesystem": true
            },
            "volumeMounts": [
              {
                "mountPath": "/tmp",
                "name": "tmp"
              }
            ]
          }
        ],
        "securityContext": {
          "runAsNonRoot": true,
          "runAsUser": 1000,
          "seccompProfile": {
            "type": "RuntimeDefault"
          }
        },
        "serviceAccountName": "payment-service-sa",
        "terminationGracePeriodSeconds": 60,
        "tolerations": [
          {
            "effect": "NoSchedule",
            "key": "novapay.io/payment-critical",
            "operator": "Exists"
          }
        ],
        "topologySpreadConstraints": [
          {
            "labelSelector": {
              "matchLabels": {
                "app": "payment-service"
              }
            },
            "maxSkew": 1,
            "topologyKey": "topology.kubernetes.io/zone",
            "whenUnsatisfiable": "DoNotSchedule"
          }
        ],
        "volumes": [
          {
            "emptyDir": {},
            "name": "tmp"
          }
        ]
      }
    }
  }
}
