{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "annotations": {
      "argo-rollouts.argoproj.io/managed-by-rollouts": "payment-service"
    },
    "name": "payment-service-active",
    "namespace": "novapay-prod"
  },
  "spec": {
    "ports": [
      {
        "name": "http",
        "port": 80,
        "targetPort": 3002
      }
    ],
    "selector": {
      "app": "payment-service",
      "rollouts-pod-template-hash": "7d95b5c448"
    },
    "type": "ClusterIP"
  }
}
